export const recipeNames = {
    A: [''],
    B: [''],
    C: ['Chilli con carne s rýží'],
    D: [''],
    E: [''],
    F: [''],
    G: [''],
    H: ['Hovězí po sečuánsku', 'Hovězí steak s batáty'],
    I: [''],
    J: [''],
    K: ['Klasická pizza', 'Kuřecí plátek s bramborami', 'Kuřecí s rýží a brokolicí', 'Kváskový chléb se sýrem a šunkou'],
    L: [''],
    M: ['Míchaná vejce na cibulce'],
    N: [''],
    O: [''],
    P: [''],
    Q: [''],
    R: [''],
    S: [''],
    T: ['Tvaroh s ovocem a ořechy'],
    U: [''],
    V: ['Vejce v rychlovarné konvici'],
    W: [''],
    X: [''],
    Y: [''],
    Z: ['']
}